### PR TITLE
Implement proper version sorting

### LINKED ISSUE #142: Issue with package version sorting when `.bcr.*` versions are involved
I've noticed that for the [zstd](https://registry.bazel.build/modules/zstd) and the [google test](https://registry.bazel.build/modules/googletest) packages there are `.bcr.1` packages that even though are more recent than the latest version and they presumably fix issues with the bazel central registry patching, they are not shown up as the latest versions nor appear in the correct order in the all versions list.

This has caused a problem specifically with zstd, as the `.bcr.1` version contains [this fix](https://github.com/bazelbuild/bazel-central-registry/pull/1394) without which we could not use that dependency, and it was not at all clear from the start we needed to get that version.

### PR DESCRIPTION
**Pull request by Wyverald**
Got bored and wanted to explore Typescript.

Tested on https://typescriptlang.org/play:

    > console.log(sortVersions(['1.2.3', '1.2.3-d', '1.2.3.bcr.1', '1.2.3rc3', '1', 'k']))
    ["k", "1.2.3rc3", "1.2.3.bcr.1", "1.2.3", "1.2.3-d", "1"] 

Partially addresses #54.

Fixes #142.

### CODE REVIEW

**Comment by Wyverald** [comment]
gentle ping @hobofan

**Comment by meteorcloudy** [comment]
Can you pleas check
```
Run pnpm prettier-check

> bcr-web-ui@0.1.0 prettier-check /home/runner/work/bcr-ui/bcr-ui
> prettier --check .

Checking formatting...
[warn] data/moduleStaticProps.ts
[warn] Code style issues found in the above file. Run Prettier to fix.
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by Wyverald** [comment]
Fixed!

**Review by meteorcloudy — APPROVED** [review]
Nice!

**Pull request merged**
